### ISSUE TITLE
Why do we have our own copy (link.yaml)?

### ISSUE THREAD

**Issue by gfenoy** [opengeospatial/ogcapi-processes#169]
Why do we maintain our own copy of the link.yaml file when it is available in [orcapi-comon](https://github.com/opengeospatial/ogcapi-common)?

**Comment by gfenoy** [comment]
Sorry, no need to list other files from [here](https://github.com/opengeospatial/ogcapi-common/tree/master/core/openapi/schemas).

**Comment by pvretano** [comment]
@gfenoy because in the publishing sequence, process will be a standard before common and a standard cannot reference a not-yet-standard.  Features, for example, also has its own copy of link.yaml.  When common become a standard, both features and processes can be amended to reference link.yaml in common.

**Comment by gfenoy** [comment]
Oh my, sorry.

I was thinking we should have gone the other way around by publishing common first.

**Comment by gfenoy** [comment]
Get my answer

**Comment by gfenoy** [comment]
@pvretano thanks a lot
