### ISSUE TITLE
Change request for the OGC Application Package conformance class

### ISSUE THREAD

**Issue by christophenoel** [opengeospatial/ogcapi-processes#176]
Hello,

I have made some improvements to the transactional extension. This is not yet an official change request of course, only a starting point for discussion.

For the deployment request (I renamed the type to Application Package for simplicity), I propose the following changes:

- Process Description is optional: with Serverless and Cloud functions in mind, the inputs/outputs can be very often deducted from the executable or runtime information (see below)
- executionUnit is renamed to processAsset: more generic as it will be often used for runtime information rather than binary or executable.
- config: I gathered the very usual/common runtime parameters used in Google/Amazon/Microsoft/Oracle Cloud platforms. See below. I assume these are not profile specific.

See model:
![Image](https://sites.google.com/site/christophenoel/_/rsrc/1618847658188/home/ogcapiprocesses-transactionalchangerequest/appPackage.png)

Configuration parameters provides hardware requirements and potentially other runtime configuration parameters:

![Image](https://sites.google.com/site/christophenoel/_/rsrc/1618847664356/home/ogcapiprocesses-transactionalchangerequest/appPackage-config.png)

For illustrating the transactional extension with other kind of package than Docker, I put the batch-git profile I'm using in a current project which consist in providing a generic git repository. The repository assume to use the server default environment (java runtime in or case) or rewrite the environment using a conda config file (for example for a Python environment).

There two more properties shown in figure below:
![Image](https://sites.google.com/site/christophenoel/_/rsrc/1618847668407/home/ogcapiprocesses-transactionalchangerequest/git-package-asset2.png)

Now see an example of deployment request for this profile:

```
{
  "processAsset": [
    {
      "gitRepo": "http://git-server/project/myproject.git",
      "command": "python3 hello.py",
      "args": "--myInput1=$input1 --myInputFile=$image.tif",
      "outputDirectory": "/outputs",
      "tempDirectory": "/tmp",
      "output": [
        {
          "id": "imageTiff",
          "globPath": "output-*.tif"
        }
      ]
    }
  ],
  "config": {
    "cpuMin": 1,
    "cpuMax": 2,
    "memoryMin": 4,
    "memoryMax": 4,
    "storageTempMin": 0,
    "storageOutputsMin": 100,
    "jobTimeout": 3600
  },
  "deploymentProfile": "http://www.opengis.net/oas-p/profiles/batch-git"
}
```

If you prefer to deploy a container, you just need to define imageRef instead of gitRepo.

**Comment by spacebel** [comment]
I forgot the proposed deployment request schema:

`
---
applicationPackage:
  type: object
  properties:
    processDescription:
      "$ref": "#/definitions/processDescriptionType"
    processAsset:
      description: Ressource holding an executable or runtime information to execute
        the process
      type: array
      minItems: 1
      items:
        type: object
        example:
          type: docker
          image: mydocker/ndvi:latest
    config:
      description: Hardware requirements and configuration properties
      properties:
        cpuMin:
          description: "Minimum number of CPU required to run the process (unit is
            CPU core). \r\nMinimum value is 1."
          type: number
        cpuMax:
          description: Maximum number of CPU dedicated to the process (unit is CPU
            core)
          type: number
        memoryMin:
          description: Minimum RAM memory required to run the application (unit is
            GB)
          type: number
        memoryMax:
          description: Maximum RAM memory dedicated to the application (unit is GB)
          type: number
        storageTempMin:
          description: Minimum required temporary storage size (unit is GB)
          type: number
        storageOutputsMin:
          description: Minimum required output storage size (unit is GB)
          type: number
        jobTimeout:
          description: Timeout delay for a job execution (in seconds)
          type: number
    deploymentProfile:
      type: string
      format: uri
      example: http://www.opengis.net/profiles/eoc/container
  required:
  - processAsset
  - deploymentProfile

`

**Comment by fmigneault** [comment]
If a custom Application Package definition is used other than CWL, I think the custom `config` should be inside what you named `processAsset`, since those are details relevant to that application, and not the "WPS process" that wraps it. 
IMO It shouldn't reside at the same level as `processDescription` or `processAsset`. 

Same is done with CWL using the `requirements` that provides similar parameters as you need (cpuMin, cpuMax, etc.) : 
https://www.commonwl.org/v1.1/CommandLineTool.html#ResourceRequirement
https://github.com/common-workflow-language/common-workflow-language/issues/587 

I question also the name `processAsset`. If there is potential change away from `executionUnit`, why not simply define it as `applicationPackage` since that is the indented content?
So the deploy would be: 

``` json
{
  "processDescription":  { "..." },
  "applicationPackage": { "<CWL> or <processAsset> or <custom>" },
  "deploymentProfile": "..."
}
```

**Comment by christophenoel** [comment]
I have explictly created this "config" element, because those properties are not application-specific.
Indeed, any kind of application might have some memory requirements, timeout delay,etc. Therefore, this needs to be declared globally.

CWL Application Package, which we initially introduced in OGC Testbed-14 is not a great application package from my point of view.

**Comment by christophenoel** [comment]
Application Package is the name I use for the placeholder of processdescrpition, processAsset and deploymentProfile.

**Comment by fmigneault** [comment]
Shouldn't OGC-API __*Processes*__ have top-level processes with a sub-`applicationPackage` definition, not the other way around? 

I think it is not the role of OGC-API Processes to specify how an Application Package content should be defined. Similarly to how GeoPackage, CWL or Dockerfile can be used to represent contained information for a specific format/standard, it is up to that AP to define relevant parameters that applies to it, and OGC-API only employs that selected standard. I think that OGC-API Processes should only concentrate on the actual definition of the description, inputs and outputs, and leave specific execution configurations to whichever standard is used for the AP, CWL being only one of them. OGC-API shouldn't try to redefine everything, since all implementation will then have to parse that `config`, and convert it back to the AP standard they decided to support. I believe the definition of my previous comment makes more sense, as that indeed extend the definition of the `Process` with the sub-`applicationPackage`, not wrap another layer on top of it. 

I think it is also not realistic to have a generic `config` at the top level that tries to accommodate for every possible scenario (Google/Amazon/etc.), because it will either (1) become a schema that never be sufficiently maintained according to all modifications anytime one of those platform change something or for every new use case, or (2) become an `Any` object that just doesn't have any specific format, like shown in the first figure. Because it is an `Any` object, it feels like the wrong way to address this issue as there are no added guidelines, just more variable fields users won't know how to fill. 

I am also somewhat confused by how the `config` is not application-specific? If not for the Application Package (script, algorithm, Docker image, or however it is implemented) that requires minimal compute time, disk space, memory, CPU/GPU, etc. to run successfully, then what dictates it? I find that it is precisely the required computation done by this App Package (aka the core of the execution) that will indicate if more or less compute power requirements are needed. 

Since the way the `config` will have to be passed down to compute units is directly related to how the App Package is defined and how it gets executed by the server, this is the exact reason why it should reside under a sub-`applicationPackage`.

**Comment by pvretano** [comment]
@fmigneault @christophenoel I just want to make sure that it is clear that the Transaction extension DOES NOT, and should not, MANDATE a specific application package format.  Rather, client and server should negotiate a mutually agreeable format.  Instead, the Transaction extension defines the `OGC Application Package` conformance class -- to which @christophenoel is proposing changes here -- and simply recommends that if this app pkg format is suitable for the purpose at hand then clients should consider using it.  However, a client is perfectly free to negotiate the use of CWL as defined in the recent est practice paper ... if the server claims to support it.  

This is similar to what OGC API Features does.  In Part 4 (Transactions) OAPIF does not mandate a specific feature encoding.  Rather it defines conformance classes for GeoJSON and GML and says that if these formats are suitable for purpose the clients should consider using them.  However, the client and the server are perfectly free to negotiate to another format (e.g. SHAPE).

Apologies for the long winded comment.  Just want to make sure that this decoupling between the mechanics of a Transaction and the description of an application package is clear.  Please carry on with your discussions ... they are very good.

**Comment by fmigneault** [comment]
@pvretano  
I totally agree with you about the AP format. It is not up to OGC-API Processes to define what is contained in the AP, nor should it care about it. 

What I want to highlight in the proposed changes by @christophenoel it that the `applicationPackage` are wrapping around the `processDescription`, which feels wrong. Being the Processes API, `Process` or `ProcessDescription` should be at the top level, and optionally have an AP under it, which the client and server agree on. The `config` should also be under that `applicationPackage`, since it is something specific the client/server agree on with that specific implementation of the extension. 

In our implementation, it is defined with CWL (and many other formats) within the `executionUnit`. I have no problem about the possibility to rename `executionUnit` to `applicationPackage`, but I disagree about `applicationPackage` becoming the top element of the body. It makes no sense to have `applicationPackage` on top, since it is a process that gets deployed and described.

**Comment by p3dr0** [comment]
I would also like to remind you that the use of CWL as the application package is described in the 
OGC Best Practice for Earth Observation Application Package available in the EOEP DWG  
  https://gitlab.ogc.org/ogc/eoap-best-practice/-/tree/master/

If you don’t see the gitlab folder please go to our DWG page 
	https://portal.ogc.org/?m=projects&a=view&project_id=599 
and opt-in for the OGC GitLab Repository

**Comment by christophenoel** [comment]
> I am also somewhat confused by how the config is not application-specific? If not for the Application Package (script, algorithm, Docker image, or however it is implemented) that requires minimal compute time, disk space, memory, CPU/GPU, etc. to run successfully, then what dictates it? I find that it is precisely the required computation done by this App Package (aka the core of the execution) that will indicate if more or less compute power requirements are needed.
> 
> Since the way the config will have to be passed down to compute units is directly related to how the App Package is defined and how it gets executed by the server, this is the exact reason why it should reside under a sub-applicationPackage

As any application has (implilictly) memory/cpu requirements, I believe this is a major benefit to abstract the technical details about how you will pass it to the backend cluster/scheduler.

The ideal transactional OGC API PRocesses server would act as follows:
* If you have a python applicaiton, you register it by providing the python git repository, unix command to start the python script, and the hardware requirements (in a standard way)
* If you have a Java application, you register it by providing the Java git repository, maybe the main class and method inputs, and the hardware requirments (in a standard way).

The user which register the application can use this same application package (Java or Python) on any server supporting the AP and not care about if the application is actually transformed to a container, executed using CWL, executed on a single node, or on a cloud cluster.

(This is already more or less what you do when you use Google Cloud or AWS Cloud functions, also referred as Serverless computing).

**Comment by fmigneault** [comment]
@christophenoel 

For (1), you provide exactly the reason why I believe `config` is not needed here. If all cloud providers are already supporting it, but with different naming conventions, it is just more boilerplate in the payload that OGC would define. If you know that [XKCD about standards](https://xkcd.com/927/), this is what `config` is starting to look like. Any implementation would need to parse that OGC-specifc `config`, to regenerate the real Google Cloud. AWS, etc. equivalent. There is no advantage from the point of view of OGC to provide the `config` directly, just adding yet another definition. 

If the server implements, let's say Kubernetes, it would be fairly simple to extract the precise value for it directly from `Process.ApplicationPackage.config` when deploying such AP, since it is exactly what that implementation is expecting, so again no advantage to expose that abstract `config` at the top. Implementation that supports X, Y, Z cloud providers need to know their precise definition/naming convention to forward parameters accordingly anyway, so they should be able to look for those specific definitions directly.

Note also that defining `config` inside `Process.ApplicationPackage.config` still allows you to define an abstraction format if this is what you want to do, since whatever `Process.ApplicationPackage` contains is server/client-specific and ignored by base OGC-API Processes. There is just no "standard format", but you shouldn't expect one anyway, since it is server/client-specific.

Even after TB14 WPS-T, TB14 ADES & EMS, TB15 and TB16, (which moved `executionUnit` a few times), I still don't think it is the good practice to have `executionUnit` (or `applicationPackage`) in the top-level. From a RESTful point of view, requesting a `POST /processes` to deploy should provide a `Process` payload, especially if it is after retrieved from a `GET /processes/{id}`. It is not RESTful (nor obvious) that POST of AP structure somehow becomes a `Process` description from it. Definitely, the process is strongly related to the AP that defines its core operation, but OGC-API Processes work with processes, not APs. 

I do not believe in : 
> what you provide when deploying/registering an application", so it does not necessarily imply a Process Description

If there are no process description, how is one supposed to execute, modify or un-deploy it? All routes refer to a `Process`.
The `Process` description encapsulates the AP retrieved that way, so the AP should also be under it during deployment.

**Comment by mr-c** [comment]
> I would also like to remind you that the use of CWL as the application package is described in the
> OGC Best Practice for Earth Observation Application Package available in the EOEP DWG
> https://gitlab.ogc.org/ogc/eoap-best-practice/-/tree/master/
> 
> If you don’t see the gitlab folder please go to our DWG page
> https://portal.ogc.org/?m=projects&a=view&project_id=599
> and opt-in for the OGC GitLab Repository

@p3dr0 Can I have an account there?

**Comment by pvretano** [comment]
@christophenoel @fmigneault @p3dr0 if I schedule a teleconference next week, can we get together to go over the discussion in this thread?  I am working on revising Part 2 now and would like to get all the details settled if we can.  I know, I know BIG ask but I would like to try.  If you agree, please indicate this with a thumbs up to this comment and I will set up a GTM.

**Comment by p3dr0** [comment]
preference for wednesday or friday

**Comment by fmigneault** [comment]
Preference for Wednesday. I will not be available Thursday/Friday.

**Comment by pvretano** [comment]
@p3dr0 @fmigneault have not heard back from @christophenoel.  Let me check his availability before I set up a meeting.  We may have to meet next week.  Please stand by ...

**Comment by gardengeek99** [comment]
I would like to be involved in this discussion, but next week would be better for me.

**Comment by pvretano** [comment]
@christophenoel, you say "in my current draft".  Is something that you have that we can look at?  Based on your comments then, the application package is composed of: 

1. An optional process description.
2. An "applicationAssets" section.
3. A "config" section describing computing resource the application needs.
4. A deploymnetProfile task indicating the profile of the application.

Is this correct?

@p3dr0 thanks for the PR.  Yes, I think the approach of an abstract model with possible encodings is the right way to go.

**Comment by christophenoel** [comment]
@pvretano Yes Peter. 

I assume that config would be something like "runtime requirements" (useful for any backend implementation/scheduler and possibly also including resource conditions, network access, ... )

The draft I'm refering is quite old, and a bit too project specific to be shared, sorry.

**Comment by bpross-52n** [comment]
SWG meeting from 2024-03-18: Overtaken by events. CWL class added to Part 2. Please open a new issue, if this still needs to be adressed by the SWG.
