### ISSUE TITLE
Idea for future evolution - status and result

### ISSUE THREAD

**Issue by christophenoel** [opengeospatial/ogcapi-processes#178]
Dear all,

A last idea (will need to switch to a big project now) for a long term enhancement of the OGC API Processes:

When submitting an execution, the response would be always a status info which optionally contains the results. The jobs/{jobsId} would also be a Status Info, and the jobs/jobId/result would disappear.

![diagram](https://github.com/spacebel/ogcapi-processes/raw/main/ogcapi-status.png)

Two consequences:

- If the server quickly execute the job, the result are available in the execution response
- When the results are available, you don't need the additional /result request
- In the execute request, you could add a "timeout" property, to wait for the result in the execute response up to that time.

Regards.

**Comment by jerstlouis** [comment]
About:

> When the results are available, you don't need the additional /result request

@christophenoel 
I just proposed something similar (same idea) in https://github.com/opengeospatial/ogcapi-processes/issues/171#issuecomment-824739111 :

> When using async with polling, the job status already has a JSON structure. Could individual outputs be linked from an array of results directly in that JSON structure? Then that could point directly to the raw responses.

**Comment by fmigneault** [comment]
I like the idea of providing the results directly in job status response if they are available. 
It should be clear in the specification that `result` object should be present *only* when the job progress is 100% and `status = succeeded`. 
That will also help bridge the gap between `sync` and `async` mode execution.

I think that `/jobs/{jobId}/result` should remain though, as it can be used by an external client to obtain the contents of the result without additional parsing of the job status to extract `result`.

**Comment by jerstlouis** [comment]
@fmigneault but the external client could be given either the direct raw links, or could parse only the relevant portion providing outputs results ignoring any other property in the JSON object -- that doesn't really make it any harder to parse.

By the way there is no `/result` defined in the specifications at the moment, it is `/results` plural.

https://docs.ogc.org/DRAFTS/18-062.html#sc_retrieve_job_results

We have run into such singular/plural mismatches many times in integration experiments (maybe it was changed in the past?) and that is a major reason why I favor to simplify things and get rid of `/results` altogether.

**Comment by fmigneault** [comment]
Indeed. There is a mismatch with/without `s` about that specific `results` item that I have encountered many times across the Testbed iterations.

And you're right also, the result is not that complicated to parse. 
I would like to keep it more as convenience because it is already available in the current specification and aligns well with the `GetResult` operation of older WPS. I would rather have a similar route that reports the `results` in both `/jobs/{jobId}` and `/jobs/{jobId}/results` than have existing instances break because `/jobs/{jobId}/results` suddenly doesn't exist for new versions, while older don't report `results` in the job status.

**Comment by pvretano** [comment]
@fmigneault @jerstlouis just created a PR #186 to make sure result/results is used consistently everywhere.  Basically the schemas and endpoints should use results (plural).

**Comment by jerstlouis** [comment]
@pvretano Thank you, that's a great step forward (from the diff I can see there was still one wrong bad (_result_ singular) example in clause 7, and the singular `result.yaml` file name did not help).

Just for the sake of clearly explaining my train of thoughts (realizing that we agreed to a feature freeze and we do want to get the spec out ASAP)...

The jist of this particular issue and my suggestion is why do we need this `/results` at all?
We already have a JSON object at `/jobs/{jobId}` which, once a job completed successfully, could directly include an array of the job's results (what is currently included in `/results`).

Whether we talk about simplification (such as removing the need for `/results`, or the #171 simple profile proposals), or providing a more comprehensive series of examples, I think we need to consider the full matrix of possbilities currently allowed by the spec:

A) response = document / raw
B) mode = async / sync
C) selecting one / more than one output
D) output's `transmissionMode` being "value" or "reference"

Are all of these combinations allowed? For example _Requirement 19_ seems to hint at the fact that response=raw is only supported in combination with sync (making response useless in async), but I don't think that is ever explicitly mentioned. Response is required per the schema, and the example right after _Requirement 16_ uses response = document.

I think a table of the possibilities (up to 16 of them) including all of the following would go a _**very long way**_ in making the specifications easier to understand and follow:
- The HTTP code of the response to the POST to `/jobs/{jobId}/execution`
- The media type of the POST response
- The content (schema or otherwise) of the POST response
- Whether a resulting `/jobs/{jobId}` (and `/jobs/{jobId}/results`) is required
- The media type of GET `/jobs/{jobId}/results`, if applicable
- The content (schema or otherwise) of GET `/jobs/{jobId}/results`, if applicable

Example requests & responses associated with each row of the table would also be useful.

**The myriad of possibilities (all 16 of them)**

1. *Raw / Sync / Single output / value*
In my heavily biased opinion, this is the simplest & easiest way to use _OGC API - Processes_, as long as the process is well-optimized & well-powered, and the data to process is of a limited size that it can complete in a few seconds.

The client POSTs to `/processes/{processId}/execution`, and the server returns a 200 with the actual data, e.g. a GeoTIFF coverage, a GeoJSON object, a JSON object following the input description schema (including a basic type like number or text string?).

In this case, though the server can feature job management, neither `/jobs/{jobId}` or `/jobs/{jobId}/results` is required.

Am I correct in this assertion? That is how I currently understand the recent draft, but some (outdated?) implementations did not  follow this approach.

Requirement 19 C says:

> If the "response" attribute of the execute request was set to "raw", the content of the response SHALL only include the **one** output selected by the execute request body.

It is ambiguous whether it means that this is still a JSON object with a single property (which still feels like a _document_ and not the _raw_ output).

Requirement 24:

> A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. The content of that response SHALL be based upon the OpenAPI 3.0 schema result.yaml.

 seems to contradict requirement 19 when "raw" is used (if the intended meaning is that the raw output should not follow the results schema), and otherwise somewhat redundant with 19 B.

2. *Raw / Sync / Multiple outputs / value*

Assuming I understand 1 right, this would require the use of multipart/form-data / RFC 7578.
I did not find whether the specifications explicitly excludes the use of multiple outputs with _raw_, but  requirement 19 C seems to hint that this is the case?

3. *Raw / Sync / Single output / reference*

What do we get back in this case? I would still expect a 200 directly with the one result, but will it just be a text/plain string? A JSON object with an "href" property? In sync mode the reference may expire early as well. Is the "by reference" mode really needed? With async, we have a `/jobs/{jobId}` and/or `/jobs/{jobId}/results` that can be passed around to whoever needs to fetch the actual data. With sync, whoever needs data can issue the sync request in the first place (the execute request can be passed instead to that requester).

4. *Raw / Sync / Multiple output / reference*

Similar to 3, but it seems that in this case a JSON array would be required rather than a single string.

5. *Document / Sync / Single output / value*

I understand this as the 200 response to the POST now being a JSON object following _results.yaml_ (unlike 1-4, if my assertions stated above are correct).

What does by value mean in this context? It's simple if the output is a basic data type or a JSON object, but if it is a GeoTIFF? Is it base-64 encoded inside the object? I wonder if we could not get rid of _transmissionMode_ and automatically return data that cannot naturally be expressed in JSON by reference, and always inline basic data types and JSON objects.

6. *Document / Sync / Multiple outputs / value*

This is much like 5, because naturally results.yaml supports multiple outputs.

7. *Document / Sync / Single output / reference*

This is mostly straightforward, except again it's quite non-sensical to link to a separate URL just to provide an inline number or string. So again I would suggest to get rid of _transmissionMode_ in favor of automatically returning by value simple and JSON object types while returning other types by reference.

8. *Document / Sync / Multiple outputs / reference*

Much like 7.

9. *Document / ASync / Single output / value*
The response to the POST is a 201 with the Location set to the job status (statusInfo.yaml).
Shouldn't it require anything about a payload in the response, e.g. including a statusInfo response?
The _Location_ in the header is the only thing guaranteed to be returned (less convenient in browser)?
Currently, a separate results.yaml, linked from statusInfo.yaml, describes the result.

The response to a GET on `/results` returns that results.yaml object (with a single output in this case). Again for data that cannot be directly represented in JSON, what does returning by value mean, base-64 encoding? I think the specification should explicitly describes this.

10. *Document / ASync / Multiple outputs / value*
This is much like 9, since it's results.yaml naturally supports multiple outputs.

11. *Document / ASync / Single output / reference*
This is much like 9, but again it seems pointless to use reference with simple & JSON types.

12. *Document / ASync / Multiple outputs / reference*
This is much like 11, since it's results.yaml naturally supports multiple outputs.

13. *Raw / ASync / Single output / value*
Is this supported / different than 9?
The response to the POST is a 201 with the Location set to the job status (statusInfo.yaml).
Is the intent to directly return a single output e.g. in GeoTIFF at `/results` ?
That would contradict Requirement 24.

14. *Raw / ASync / Multiple outputs / value*
Supported / contradicting req 24? Similar to 13, but this could be using multipart/form-data like 2.

15. *Raw / ASync / Single output / reference*
Supported / contradicting req 24? Similar questions as 3 whether it is a string or JSON object.

16. *Raw / ASync / Multiple outputs / reference*
Supported / contradicting req 24? Similar questions as 4 whether it is a JSON array.

So what I was proposing here and in #171 is to greatly simplify this whole complicated matrix of possibilities into the following two primary use cases:

**A) Combined 1/2/3/4: Sync/Raw** (output media type or multipart), Everything by value so the result set is self-contained, Multi-Part for multiple outputs
**B) Combined 9/10/11/12: Async/Document** (using result.yaml), Automatic value/reference based on whether it's a simple or JSON type

The following could be considered as well:

_Combined 5/6/7/8: Sync/Document_ (using result.yaml), Automatic value/reference based on whether it's a simple or JSON type
_Combined 13/14/15/16: Async/Raw_ (output media type or multipart), Everything by value so the result set is self-contained, Multi-Part for multiple outputs

but:
- with Sync/Document the server would be forced to somehow keep the results alive even after the client fully received the execution response (which is very cumbersome if it does not implement job management), and
- I don't see any value in Async/Raw, which would require multipart for multiple outputs and make it harder to access an individual output, plus it would prevent from directly embedding `/jobs/{jobId}/results` within `/jobs/{jobId}`.

If sync is always raw and async always document, then we could get rid of `response`, and per this suggestion we could also get rid of `transmissionMode` and `/jobs/{jobId}/results` (for _document_ it would be directly embedded in `/jobs/{jobId}`).

And we bring the complexity from 16 combinations down to 2.

If we decide not to to do this simplification, I believe we still badly need this table that clearly and unambiguously explains exactly how each of these 16 possibilities work, because it is still not clear to me, and I don't believe that is from a lack of reading or trying to understand the specification.

**Comment by jerstlouis** [comment]
I prepared two tables that summarizes this in a much more visual manner.

The table on the first page is how I currently (miss?)understand the current specifications.
If we stick to the status quo, it would be great to verify that we agree on the understanding and include such a summary of the possibilities.

The table on the second page is the simplification I propose, which I believe might actually turn out easier to go ahead with than fixing the existing ambiguity of all the current possibilities.
[OGC API - Processes - Current (lack of) understanding and simplification proposal.pdf](https://github.com/opengeospatial/ogcapi-processes/files/6463587/OGC.API.-.Processes.-.Current.lack.of.understanding.and.simplification.proposal.pdf)

**Comment by pvretano** [comment]
@jerstlouis I am not seeing the "missed" result.yaml you reference in the PR.  Lets merge and I'll do one last sweep to make sure that result/results are all consistent.

**Comment by jerstlouis** [comment]
@pvretano No no I was not saying that you missed anything, I was saying that you caught one last singular result that had _previously_ been missed.

**Comment by pvretano** [comment]
@jerstlouis ah OK... LOL! ;)

**Comment by fmigneault** [comment]
@jerstlouis Very nice summary. It does indeed help putting things into perspective!

Can you develop of the following. 
Why is `Media type` of POST execute changing based on `sync`/`async`? Does it refer to the request `Accept` header, the request body `Content-Type`, returned response `Content-Type` or the `type` in the process input definitions?  If the last, how is the type selected in case of multiple data/value inputs of different types?  I thought the result was always JSON because we need the mapping of Output ID to result value? Maybe I assumed wrong?

The response of `async` execute technically only enforces the `Location` header: https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/responses/ExecuteAsync.yaml
But I agree that `statusInfo.yml` content is clearer and this is what we return in our implementation on top of the `Location`.

**Comment by jerstlouis** [comment]
@fmigneault Thanks @fmigneault . You bring up a good point:

> Does it refer to the request Accept header, the request body Content-Type 

It referred to the returned response Content-Type. The request body Content-Type is understood to always be application/json, but the table (or a side note) could potentially explicitly say that. Client & server could negotiate a different returned Content-Type with the same information using the request Accept header, but application/json is the default, and the way the requirements are specified it may be the required / only valid response content type.

> Why is Media type of POST execute changing based on sync/async? 

Well the server returns something very different in both cases. As noted in the table, currently the specification does not say anything at all about what payload is returned in async. It seems assumed that nothing is returned, or at least the client cannot rely on anything being returned other than the Location in the header as we both pointed out.

For synchronous (for which I believe response raw/document was originally intended), the whole purpose of the response parameter is to determine what is returned. Raw means that the response is directly the media type of the input, while document means returning from the execute POST the same JSON document (results.yaml) that you will get in async mode from GET `/jobs/{jobId}/results`. That is how I always interpreted the meaning of a `raw` output (e.g. it's directly the produced GeoTIFF), but I don't think the specification expressed this clearly at all.

> returned response Content-Type If the last, how is the type selected in case of multiple data/value inputs of different types? 

No, when necessary (i.e. input passed by reference?), the input content type is specified inside the execute request for each input 

> I thought the result was always JSON because we need the mapping of Output ID to result value? Maybe I assumed wrong?

I believe you assumed wrong, but I have seen implementations doing both, so you are not the only one and the specification was ambiguous, especially Requirements 19 and 24. @pvretano mentioned having clarified those requirements already today.

When multiple outputs are returned, I suggest `multipart/form-data` could be used (if that combination is allowed).

All these ambiguities and lack of clarity is why I am hoping to at least polish this table and agreeing on it within the SWG, and including it in the specifications.

And potentially taking the further step of simplifying things as per the second page table which in my opinion maintains all functional capabilities while greatly simplifying both understanding and implementation.

**Comment by fmigneault** [comment]
@jerstlouis  I see, good summary and good initiative.

You're probably right about using `multipart/form-data`. I don't see how multiple outputs of completely different formats could be combined in a single response otherwise if selection of response `Content-Type` is based on the input. 

Maybe `Accept` can be allowed in the case of only a single output to obtain it directly, but this is still tricky in cases of array of values under some single output ID.

**Comment by bpross-52n** [comment]
Done.

**Comment by christophenoel** [comment]
Sorry for the delay, but I cannot see how my initial question is addressed in the spec ?
Thanks.

**Comment by christophenoel** [comment]
I would say, that the status/result can be mixed behind a single endpoint ? Thanks.

**Comment by christophenoel** [comment]
Hi Francis,

I agree to disagree ! :) 

From a REST point of view, I consider that the server creates two kind of resources: jobs and outputs (when the job is completed).  When status = completed, the client get access to the links of each output resource.

[...of course, this might have additional side effects related to all the options (raw, document, value, reference) which I still regard as a XML API heritage which is against the OGC Web API Guidelines Principle #2 – Keep the API Simple and Intuitive]

**Comment by jerstlouis** [comment]
@christophenoel 

> all the options (raw, document, value, reference) which I still regard as a XML API heritage which is against the OGC Web API Guidelines Principle https://github.com/opengeospatial/ogcapi-processes/issues/2 – Keep the API Simple and Intuitive]

I think we are all in agreement with this, this is why it was addressed in #217 and PR #272 (which also fixes addherence to OGC API Web Guidelines Principles [number 9](https://github.com/opengeospatial/OGC-Web-API-Guidelines#principle-9--use-of-http-header) and [number 10](https://github.com/opengeospatial/OGC-Web-API-Guidelines#principle-10---allow-flexible-content-negotiation)).

However, with 217 fixed / 272 applied, there are still different resources for the job status and the job outputs. If all outputs are large binary objects, then they will likely simply be linked from an `application/json` retrieved from `/results`. However, for outputs that can be expressed as small JSON objects, that would be found directly inline at this JSON document from retrieving `/results` as `application/json`. If there are several such small JSON objects, then an advantage of the separate `/jobs/{jobId}` resource for polling the status is that those results objects do not need to be included in the status response.

This is also still in line with your last description:

> From a REST point of view, I consider that the server creates two kind of resources: jobs and outputs (when the job is completed). When status = completed, the client get access to the links of each output resource.

One reason for maintaining the plural results resource (separate from status), is that this could also be negotiated as a `multipart/` or `application/zip` with all the results in there, in addition to an `application/json` document that may contain links to large binary files and/or small JSON objects/values.

**Comment by bpross-52n** [comment]
This should be fixed by #272
