### ISSUE TITLE
Change request for statusInfo : add date time stamps for creation and last update 

### ISSUE THREAD

**Issue by p3dr0** [opengeospatial/ogcapi-processes#184]
I propose to add two new **optional** properties in the statusInfo yaml to deal job creation and last status update
This would be the property `created` and `updated` (both of type `date-time`)

The `created` is the date time when the job was `accepted` and the `updated` is the date time when the job last changed status.

**Comment by pvretano** [comment]
@fmigneault I think `started` is a good addition.  I you have `updated`, which is the last time the job status was updated, you don't need `finished`.  When the  `status` is `completed`, the `updated` date will be the timestamp when the process finished.  Similarly, `duration` seems unnecessary too since `updated-started = duration`... no?

**Comment by bpross-52n** [comment]
Fixed.
