### ISSUE TITLE
What to do when mixing transmission mode and response ....

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-processes#204]
What should a server do if the requested outputs are a mix of different transmission modes (value/reference) and responses (document/raw).  For example...
```
 "outputs": {
    "CENTRE": {
      "format": {
        "mediaType": "text/xml"
      },
      "transmissionMode": "value"
    },
    "STDDIST": {
      "format": {
        "mediaType": "application/json"
      },
      "transmissionMode": "value"
    },
    "BBOX": {
      "format": {
        "mediaType": "application/json"
      },
      "transmissionMode": "reference"
    }
  },
  "response": "raw"
}
```
@gfenoy solution is to use a multipart MIME docuement with 200 status core where the part that is related to the "reference" output value sues the Content-Location header to point to the content.

This case is not actually covered in Table 7 in the specification so we will need to expand that table or include some other normative text to handle the case of mixing transmission modes and responses.

Here is an example for @gfenoy where all the transmission mode are "reference" that uses the Content-Location header to reference the content of each part.

```
----4221d35e-c85f-11eb-ae44-0242ac190006
Content-ID: CENTRE
Content-Description: Mean Centre
Content-Type: text/xml; charset=utf-8
Content-Location: 
http://tb17.geolabs.fr:8088/temp///Output_CENTRE_4221d35e-c85f-11eb-ae44-0242ac190006_1.xml

----4221d35e-c85f-11eb-ae44-0242ac190006
Content-ID: STDDIST
Content-Type: application/json; charset=utf-8
Content-Location: 
http://tb17.geolabs.fr:8088/temp///Output_STDDIST_4221d35e-c85f-11eb-ae44-0242ac190006_2.json

----4221d35e-c85f-11eb-ae44-0242ac190006
Content-ID: BBOX
Content-Type: application/json; charset=utf-8
Content-Location: 
http://tb17.geolabs.fr:8088/temp///Output_BBOX_4221d35e-c85f-11eb-ae44-0242ac190006_3.json

----4221d35e-c85f-11eb-ae44-0242ac190006--
```

**Comment by jerstlouis** [comment]
I believe there is a strong use case for "document" response and mixed ref/value transmission outputs.
(So much so that I was initially suggesting that binary outputs always be by reference, while simple types be by value).

For "raw" response, my interpretation based on what was in the table would be that:
- All outputs set to transmit by "value" would be together included the multipart body of the response
- All outputs set to transmit by "reference" would be in the response header as links

I think this makes the most sense considering that this is how it works when not mixing them, and we could just add clarifications that this is how it works in this case.

**Comment by bpross-52n** [comment]
Peter drafts a PR for this.
