### ISSUE TITLE
openapi.json specification does not include jobList parameters

### ISSUE THREAD

**Issue by mike-gangl** [opengeospatial/ogcapi-processes#410]
I made the same comment on another's issue: https://github.com/opengeospatial/ogcapi-processes/issues/408#issuecomment-2103166856

The Job List (`/jobs`) endpoint  contains query parameters that allow for the filtering of jobs based on 

- type
- process_id
- status
- datetime
- minDuration
- maxDuration
- limit

yet none of these are included in the openapi.json spec included in this repository. What's the best path forward for including those? The previous wps specification had the `/processes/{process_id}/jobs` endpoint for filtering based on the Process ID- i prefer this new filtering on all jobs method, but was unable to use the openapi.json files to create the appropriate endpoints.

**Comment by fmigneault** [comment]
They are not part of the schema because they are considered "extensions" of the minimal functionalities required by "Core".  

See https://docs.ogc.org/is/18-062r2/18-062r2.html#toc9

> The main requirements class is:
> 
>   - [Core](https://docs.ogc.org/is/18-062r2/18-062r2.html#rc_core).
> 
>   The Core specifies requirements that all Web APIs have to implement.

> Three additional conformance classes are specified that extend the basic functionality of an API:
>
>   - [Job list](https://docs.ogc.org/is/18-062r2/18-062r2.html#rc_job-list), and
>   - [Callback](https://docs.ogc.org/is/18-062r2/18-062r2.html#rc_callback), and
>	- [Dismiss](https://docs.ogc.org/is/18-062r2/18-062r2.html#rc_dismiss).

One has to look at the `/conformance` endpoint and see if the server indicates that it supports 
`http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/job-list` to expect these filtering parameters to be respected.
